# Dockerfile for Backend
FROM golang:1.22.1-alpine3.18 AS builder
WORKDIR /server
# COPY server /server
RUN go build -o /go/bin/server

FROM alpine:3.18.6
COPY --from=builder /go/bin/server /go/bin/server
CMD ["/go/bin/server"]