services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    working_dir: /webapp
    volumes:
      - ./webapp:/webapp
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: apple
      POSTGRES_DB: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql # 确保 init-db.sql 文件在项目根目录下
